### ISSUE TITLE
filter explode with attack 0.0

### ISSUE THREAD

**Issue by redFrik** [chaosprint/glicol#24] opened 2021-07-08 10:51 UTC
Seems like the reverb and/or RLPF are blowing up with an attack time of 0.0.

Steps to reproduce:
* run the example on frontpage ( https://glicol.org/ )
* change envperc attack from 0.01 to 0.0
* update

-> no sound. Run and stop does not help. i can only get the sound back if i refresh the page.

(macOS 10.14, Firefox 89)

If i take out the plate and the filter i can use an instant attack.

The example with effects removed. This works...
```
~a: choose 48 55 51 58

~b: choose 36 60 0 0 0 0 0

// how about changing the speed to 4.0 and 
//click the update button above?
~trigger: speed 8.0 >> seq ~a ~b >> mul 2.0

~env: ~trigger >> envperc 0.0 0.1 >> mul 0.2

~pitch: ~trigger >> mul 261.626

lead: saw ~pitch >> mul ~env
>> mul 0.6

~cut: squ 0.5 >> mul 3700.0 >> add 4000.0
```

(i'm completely new to Glicol so sorry if i'm missing something obvious here)

**Comment by chaosprint** [comment] 2021-07-10 16:51
Thanks for reporting this issue.
I have looked into it and it turns out that it is caused by the algorithm in the env calculation where the attack or decay will be used for division. If either attack or decay is 0, then the output will be a `NaN`. When sending this  `NaN` to the filter it causes the issue.
Now it is fixed in the new version with an if statement.
Nevertheless,  I recommend not to use 0 for env attack or decay. It will cause a sudden jump in amplitude and often leads to a popping sound.

**Comment by redFrik** [comment] 2021-07-10 17:17
thanks.  yes, NaN makes sense.
i use 0 attack time all the time in other systems and like it.  besides the filter will (should) smooth it out.

**Closed** 2021-09-20 10:50 UTC
Labels: bug
